### ISSUE TITLE
General cleanup

### ISSUE THREAD

**Issue by ChShersh** [kowainik/universum#13]
* `list`
* `Lifted.ST`
* `getContents`
* `interact`
* `getArgs`
* `note`

**Comment by kilianovski** [comment]
Why `getContents` considered harmful?

**Comment by wbadart** [comment]
Any recommendations for a safer/ saner `interact`?

**Comment by chshersh** [comment]
@wbadart This depends on your use-case. The default `interact` for `String` is lazy which makes it work only for specific use-cases. I recommend reading the following SO question and answer that explains low-level details:

* https://stackoverflow.com/questions/16799755/haskell-interact-function

You can try using `interact` for lazy `Text` or lazy `ByteString` but the documentation doesn't describe the behaviour precisely.

My general advice would be to not use `interact` at all, and rewrite the application in a different way.

**Comment by wbadart** [comment]
Gotcha. Thanks for the tips!
